paths:
  train_csv: "/full/path/on/your/vm/to/processed_translated_train.csv"
  test_csv: "/full/path/on/your/vm/to/processed_translated_test.csv"
  trained_model_output_dir: "./output_model_dir"
  submission_dir: "./output_submission_dir"

model:
  name: "microsoft/deberta-v3-base"

training:
  max_length: 128
  train_batch_size_per_gpu: 16 
  inference_batch_size_per_gpu: 32
  num_epochs: 3
  optimizer:
    use_muon: false
    adamw:
      lr: 3.0e-4
      betas: [0.90, 0.95]
      weight_decay: 0.01
    muon:
      lr: 0.02
      momentum: 0.95

flags:
  perform_training: true
  perform_inference: true